# Generated by Django 4.2.3 on 2023-08-08 10:19

import bankapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankform',
            name='material',
            field=models.CharField(choices=[('credit', 'CreditCard'), ('debit', 'DebitCard'), ('cheque', 'ChequeBook')], default='credit', max_length=15),
        ),
        migrations.AlterField(
            model_name='bankform',
            name='name',
            field=models.CharField(max_length=100, validators=[bankapp.models.validate_name]),
        ),
    ]
